sudo: required
language: minimal

services:
  - docker

before_install:
  - docker build -t lohmag/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run lohmag/react-test npm test -- --coverage

after_success:
  - docker build -t lohmag/multi-client ./client
  - docker build -t lohmag/multi-server ./server
  - docker build -t lohmag/multi-nginx ./nginx
  - docker build -t lohmag/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push lohmag/multi-client
  - docker push lohmag/multi-server
  - docker push lohmag/multi-nginx
  - docker push lohmag/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-870665420981
  bucket_path: docekr-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
